### ISSUE TITLE
Mock location

### ISSUE THREAD

**Issue by Aashiqsk01** [smarques84/MockLocationDetector#136]

**Comment by Aashiqsk01** [comment]
Mock location delete

**Comment by AlliGoogle12** [comment]
When i use fake gps android show younare using mock location how can i fix
Please tell me

**Comment by Mohjo900** [comment]
Yes I need help 


Sent from the all new AOL app for iOS


On Monday, November 25, 2024, 1:55 PM, AlliGoogle12 ***@***.***> wrote:



When i use fake gps android show younare using mock location how can i fix
Please tell me
